### ISSUE TITLE
Slight change to DAE export

### ISSUE THREAD

**Issue by zrksyd** [jam1garner/Smash-Forge#109]
This should be at the beginning of a DAE even before the COLLADA tag, but it's absent from those exported from Forge.
`<?xml version="1.0" encoding="utf-8"?>`
Keep in mind I've added this tag before manually to a Forge DAE and some programs, like Brawlbox, that previously couldn't could open the DAE.

**Comment by jam1garner** [comment]
Fixed in commit 55f7ac1797795ef6e351408570c9359e1bb1aadc
