### ISSUE TITLE
Maya .anim files not saving / loading properly.

### ISSUE THREAD

**Issue by TabuuForteAkugun** [jam1garner/Smash-Forge#11]
Geez, I give you lots of problems, huh? I just want this app to be great. ^_^

So yeah, now I can't use .anims generated from this anymore. Mario's Wait1 and others shorter than 60 frames would work, but now none of them load properly at all. I get the correct frame counts but no data is actually saved. The model remains in the T pose for the entire duration of the animation, and in Maya, they import instantly but there's no frame data. No errors or crashes, they just plain don't work. Same thing when imported back into SAT.

**Comment by Ploaj** [comment]
Yeah, export was broken from an update. I just made a fix but it needs to be tested. Let me know if it's working again!

**Comment by TabuuForteAkugun** [comment]
Thanks, Ploaj, you just saved my butt. Now not only is it working, but animations with more than 60 frames don't hang Maya anymore. Thanks!

**Comment by TabuuForteAkugun** [comment]
Oh...kay. I've got another problem.

They don't always export properly. I tested it on Giga Bowser, to be greeted with this:

![screenshot 731](https://cloud.githubusercontent.com/assets/22761617/19826328/4bab833c-9d55-11e6-92c7-5c401f64f544.png)

**Comment by TabuuForteAkugun** [comment]
@Ploaj Animation importing seems to be on the fritz again with the latest commit. They're back to freezing up Maya when over 60 frames... But before that, the problem above persisted. Only frame 1 exported well then I got the mess in that Giga Bowser export.

**Comment by TabuuForteAkugun** [comment]
I have another point to add to this: sometimes, some bones disappear along with their skinned model parts when importing as ANIM.

**Comment by TabuuForteAkugun** [comment]
This is still a huge problem. Anim files longer than 60 frames simply refuse to export/import properly.

I need to be able to use them. :)

**Comment by TabuuForteAkugun** [comment]
Struz generously fixed this. Closing.
