### ISSUE TITLE
Smash Forge crashes when viewing certain animations

### ISSUE THREAD

**Issue by Filumbitu** [jam1garner/Smash-Forge#129]
After opening a character and selecting the main.pac animations.

Sometimes throws an "Index out of range" error, sometimes just close without any error.
It seems to depend on the character, I tested three (Greninja, Marth, Ness) and only Greninja and Marth crashed Forge. 

Wait2, EscapeF/B, FallSpecialF/B are a few of the animations that cause the crash, I didn't test them all so there's probably more.

**Comment by Ploaj** [comment]
I tested on the current version and they all seem fine. This was caused by a fix I made for some previously error-ed omo files that I have now removed.
