### ISSUE TITLE
I can't see stage background models when I open them.

### ISSUE THREAD

**Issue by Escope12** [jam1garner/Smash-Forge#13]
When I open a stage .nud model or .mdl0, I can only see the bones.
![i can only see bones](https://cloud.githubusercontent.com/assets/8963276/19871866/2e94e498-9f8d-11e6-88a5-cb30a6020883.png)

**Comment by Demonslayerx8** [comment]
this 1 is a simple thing...
the viewer doesnt render models that are HUGE af

**Comment by jam1garner** [comment]
Also mdl0 does not support models right now, only the bones. If the nud issue persists with non-background models, open another issue and link the nud in question, thanks!

**Comment by Escope12** [comment]
Thanks for the tip.
