### ISSUE TITLE
Crashes while trying to open Luigi's Grab [FitLuigiBodyMainE00Catch.omo]

### ISSUE THREAD

**Issue by ThatTrueStruggle** [jam1garner/Smash-Forge#141]
I opened Luigi's character folder in the newest version of SmashForge (https://github.com/jam1garner/Smash-Forge/commit/4771476a4f27536a875e78691e3e2a01f2a61981) and it crashed and gave me this error: https://hastebin.com/raw/izuquwuhuf

From reading the code it looks like it may be some kind of index error? 
https://github.com/jam1garner/Smash-Forge/blob/0fe90f1aa6e2bf4a292e6a8d4ca5ad8ffb7917df/Smash%20Forge/ACMDScript.cs#L823

**Comment by ScanMountGoat** [comment]
fixed
