### ISSUE TITLE
How exactly do you use this?

### ISSUE THREAD

**Issue by xanek** [jam1garner/Smash-Forge#15]
I have a dumped game, but I don't specifically understand how to operate the program itself.
What files exactly do you need specifically to get started, as I have opened up a model.nud and motion.mtable but don't really know what other files to open, as there are multiple animation files and opening multiple/certain ones give an error.

Is there any basic guide or instructions to follow?

**Comment by jam1garner** [comment]
http://www.reddit.com/r/customsmash/comments/5bheel/anyone_know_how_to_use_smash_forge/d9p7et8
