### ISSUE TITLE
Cannot open Kirby Hats (And other non-character models)

### ISSUE THREAD

**Issue by zorakirby** [jam1garner/Smash-Forge#154]
I've only tested the models for Ike, Zelda, and Wario but none of these Kirby hats will open on the current version of smash forge. They worked on previous versions.

Edit: this includes other non-character models like separate weapon models, etc

"Index was outside the bounds of the array"

**Comment by ScanMountGoat** [comment]
Submit another issue if it comes up again. A lot has changed since posting.
