### ISSUE TITLE
Animations not playing on certain character .nud's

### ISSUE THREAD

**Issue by SupremeDevice** [jam1garner/Smash-Forge#16]
Animations will cause Smash Forge to crash on certain character .nud files.
I tested the following characters:

- **_Ganon_**
- Mario
- Captain Falcon
- Megaman
- **_Bayonetta_**
- Lucas
- Donkey Kong

Bayonetta and Ganon main body .nud's will crash the game when you try to play an animation, however their bones will animate correctly if you select their .vbn or any of their other models (i.e. Ganon's final smash, Bayo's hair, etc.)

**Comment by Ploaj** [comment]
Sorry about that, we are currently in progress of reorganizing, and a recent update broke hitboxes and animations. 
I have fixed the problem for now. Thanks for letting us know!
