### ISSUE TITLE
Merging submodels together destroys bone weights

### ISSUE THREAD

**Issue by zorakirby** [jam1garner/Smash-Forge#163]
I don't know whats going on but when I merge sub-models together (so there are multiple "polygon entries) and then load the model in-game, the merged part (the second polygon entry) moves completely wrong, almost as if the bone weights/movement is multiplied by 2. The model works completely fine in smash forge. This didn't happen with the older versions (around October or so).

Could I get a download for the older version from around that time for now?

**Comment by Demonslayerx8** [comment]
use the December 25th build of Smash Forge, which can be found in the S4M
discord server, in the smash_forge channel and located in the pins

**Comment by zorakirby** [comment]
I can't actually seem to find the smash_forge channel on discord (I've also never used discord before now). Where do I find it?

**Comment by zorakirby** [comment]
Sure enough, reverting to the old smash forge version and doing the exact same steps fixed it.
