### ISSUE TITLE
Taiko NUDs

### ISSUE THREAD

**Issue by Deathmaw** [jam1garner/Smash-Forge#169]
I know this is aimed at Smash but the 3 Taiko titles on Wii U also use .nud but the models don't appear to render, the model list gets displayed with each element but nothing in the viewport.

Was hoping this could be fixed since I don't really see anything else out there aiming to open NUD files.

**Comment by Demonslayerx8** [comment]
you can use the nud script for 3ds max made by RTB to import the taiko models.

**Comment by Deathmaw** [comment]
Thanks for the heads up, I did search but guess I just missed it.
