### ISSUE TITLE
I know I reported this issue but the stage animations still don't play properly.

### ISSUE THREAD

**Issue by Escope12** [jam1garner/Smash-Forge#17]
I know I reported this issue but the stage animations still don't play properly. The bones for the stages don't move. Will this be fixed in the next update? I'm sorry for reporting this again.
![2016-11-10_17-11-27](https://cloud.githubusercontent.com/assets/8963276/20250993/17cb3838-a9e3-11e6-95d3-9b8d3e77e6ea.gif)

**Comment by Demonslayerx8** [comment]
is it a original smashu stage + animations, or a MDL0 and chr0 converted file?

**Comment by Escope12** [comment]
It is an original SmashU Stage Animation.

**Comment by Demonslayerx8** [comment]
Which stage and animation is it?

**Comment by Y2K-x** [comment]
Closing this issue. Please do not recreate a issue that is still open, just use that issue if you have any more problems. Thanks.
