### ISSUE TITLE
I can't find the Textures List?

### ISSUE THREAD

**Issue by Mashauree** [jam1garner/Smash-Forge#192]
So I can't really find the textures list on the top left of the program. I just imported a new model from 3ds max and everything seems to works alright, just can't use the NUT Editor. Can someone help me out?

![help](https://user-images.githubusercontent.com/39282815/40026841-44061c46-5794-11e8-846d-0e74e97d5d05.PNG)

**Comment by ScanMountGoat** [comment]
There is a discord you can join for help linked on Gamebanana.
