### ISSUE TITLE
Exported SMD animations don't export bone scale data

### ISSUE THREAD

**Issue by legoj15** [jam1garner/Smash-Forge#204]
Bones move properly, but on animations like the Bobomb pre-explode animation, the scaling animation isn't present when imported into blender (or when compiling for Source):
Smash Forge:
![forge](https://user-images.githubusercontent.com/7399802/41066961-cf269d12-69b1-11e8-9db1-8a9a5a60d2ab.gif)
Blender/Source Engine:
![blender](https://user-images.githubusercontent.com/7399802/41066968-d746e97a-69b1-11e8-8b0c-dfb81cd61580.gif)
(ignore the speed difference)

**Comment by Ploaj** [comment]
The SMD file format does not support bone scaling.
https://developer.valvesoftware.com/wiki/Studiomdl_Data

**Comment by legoj15** [comment]
Interesting, good to know.
