### ISSUE TITLE
Animations (PAC) not saving properly

### ISSUE THREAD

**Issue by SuperMarioDaBom** [jam1garner/Smash-Forge#21]
It appears that animations aren't saving properly. I edited one bone rotation just to see how things work, and this ended up happening:
![wiiu_screenshot_tv_0144f](https://cloud.githubusercontent.com/assets/19657053/20652617/3ffb360e-b4b1-11e6-9f48-7e8bb08a65c2.jpg)
I'm hoping this can get fixed. I really do want to mess with the characters as much as possible! Also, the NUT textures appeared to not convert properly, as they render corrupted. Just thought I'd give a heads up.

Thanks,
SuperMarioDaBom

**Comment by Ploaj** [comment]
This has been fixed with a recent update; I don't remember which one though.
