### ISSUE TITLE
can not upload model.nut files

### ISSUE THREAD

**Issue by Masterkal99** [jam1garner/Smash-Forge#217]
When I drag a model.nut extracted from Smash explorer onto Forge it will not load any of them.

**Comment by ScanMountGoat** [comment]
It still works on my machine. Does this happen with all nut files? Make sure you're on the latest version of Smash Forge.

**Comment by Masterkal99** [comment]
Hey the issue is fixed thank you for replying to me. It did not work on the latest build 9 days ago with model.nut files that are for stages
