### ISSUE TITLE
Still no hitboxes for Roy's attacks

### ISSUE THREAD

**Issue by xanek** [jam1garner/Smash-Forge#22]
It's been weeks since i've reported this to @jam1garner on discord that the hitboxes for Roy's attack don't appear on Smash Forge and told me that he was going to notify @Sammi-Husky about this. I assume this is a problem on other characters too.

I have walked through the steps with jam1garner on how to load a character with their animations in but haven't been able to get it to work.

Though i've seen an image on twitter of someone switching the hitboxes for Roy's flareblade from the fully charge swapped with the uncharged and they were able to get that hitbox to show up, but the rest don't work correctly.

**Comment by struz** [comment]
Roy currently works. Make sure that you use the "File>Open>Open Character" menu option to open the characters base folder (e.g. "fighters/roy"). This ensures that the right assets have been opened to show hitboxes.

![roy_fsmash](https://user-images.githubusercontent.com/7187551/26870656-05cd283a-4bb4-11e7-8d59-8bf81e8f3620.gif)
