### ISSUE TITLE
Parameters,Movesets,Textures don't appear in the latest version of Smash Forge

### ISSUE THREAD

**Issue by Thermalax** [jam1garner/Smash-Forge#220]
I looked at so many tutorials on how to view hitxboxes,parameters etc. But they all seem to use the older version of smash forge. What happen to those options?
![capture](https://user-images.githubusercontent.com/41085584/42534968-d93a47bc-8429-11e8-98ba-327c042728a3.PNG)

**Comment by ScanMountGoat** [comment]
You'll have to be more specific. None of those features are gone.

**Comment by Thermalax** [comment]
Here is an older screenshot of smash forge from Ruben's tutorial. In the screenshot there are a lot more options on the top of the menu then there are in the latest version. I would like to know where these features have moved.
![](https://ssbworld.com/images/blog/uploads/blobid1499389805111.png)

**Comment by ScanMountGoat** [comment]
Check the wiki for where to find things. We won't remember everything that's changed over many months of development.

**Comment by Thermalax** [comment]
I have, it led me to this [tutorial ](https://ssbworld.com/blog/127/how-to-use-smash-forge-for-character-hitboxhurtbox-and-stage-visualization)and it hasn't been updated either.

**Comment by Thermalax** [comment]
Do you happen to have an older version of this program?

**Comment by ScanMountGoat** [comment]
That page hasn't been updated. The rest of the wiki is more up to date. We don't provide older versions because you can build any version in Visual Studio.

**Comment by ScanMountGoat** [comment]
I'm going to close this. This is intended for bugs rather than help using the program. You can find people to help in the Smash 4 modding discord.
