### ISSUE TITLE
"Open Stage" causes Forge to crash.

### ISSUE THREAD

**Issue by KillzXGaming** [jam1garner/Smash-Forge#23]
This possibly occurred with the nut editor feature:

![Log](http://i.imgur.com/94okz0I.png)

I haven't tested all stages but this occurs in the Mario Kart one and a few others.

Edit: New discovery. Roy also will no longer open as this bug also occurs. Happens from the nut file. 

My specs:
CPU i5 4670
GPU gtx 970
RAM 8gb
OS Windows 10

**Comment by Ploaj** [comment]
This should be fixed now, but I'm not 100% sure.
If it crashes somewhere else re-open this.
