### ISSUE TITLE
BFRES shader compilation error on NVIDIA GPUs

### ISSUE THREAD

**Issue by slashiee** [jam1garner/Smash-Forge#238]
Using the latest commit debfdecb5a91af5d4982d7cc36b43cf26631e617, BFRES models simply do not appear. My GPU is a NVIDIA GeForce GTX 1060.
![2018-08-06_13-07-06](https://user-images.githubusercontent.com/15317421/43738476-9eb01ff8-9979-11e8-8069-ddf7ff5b44e9.png)
[BFRES Error Log.txt](https://github.com/jam1garner/Smash-Forge/files/2263942/BFRES.Error.Log.txt)
[Point Error Log.txt](https://github.com/jam1garner/Smash-Forge/files/2263943/Point.Error.Log.txt)

**Comment by ScanMountGoat** [comment]
This seems to only be an issue with Nvidia Geforce gpus.

**Comment by KillzXGaming** [comment]
Try the latest build now, the issue should be fixed.

**Comment by slashiee** [comment]
Can confirm the issue is fixed
![2018-08-07_17-01-30](https://user-images.githubusercontent.com/15317421/43808799-8a05466a-9a63-11e8-9273-f52b15d6f652.png)
