### ISSUE TITLE
BFRES .anim exports don't work

### ISSUE THREAD

**Issue by Makiah** [jam1garner/Smash-Forge#239]
Here we see a wild bear trudging across the savanna...
![image](https://user-images.githubusercontent.com/10727824/43726205-569de04a-9953-11e8-8a13-e3306a83c3f3.png)

Dear me, look!  A wild animation file exported from Smash Forge!
![image](https://user-images.githubusercontent.com/10727824/43726278-94c06a8c-9953-11e8-8e28-ea9ea4a0e274.png)

The two enter onto the battlefield... who will triumph?  
![image](https://user-images.githubusercontent.com/10727824/43726370-d41a6a0c-9953-11e8-8a2c-56b8faec0cf0.png)

![image](https://user-images.githubusercontent.com/10727824/43726418-f674b120-9953-11e8-9953-2dcf53ea250e.png)

Ah, the difficulties of life in the wild.  It's the circle of life, after all!  

On a more real note, maybe this ties into #15: it seems as though the animation isn't correctly linked to the model's actual bone positions.

**Comment by KillzXGaming** [comment]
Just to be sure, you have all the bones selected before importing correct?

**Comment by Makiah** [comment]
Yeah, I had to do Select > All by Type > Joints and then import the animation, or Maya says that it can't apply the animation.  I think that you suggested doing this on Discord, which fixed the import issue but resulted in this new issue.

**Comment by Makiah** [comment]
Ohhhh ok so for those facing a similar issue, you have to select the "Root" joint and then import the animation, my guess is that Select > All Joints results in every animation being applied to every joint... maybe?

![image](https://user-images.githubusercontent.com/10727824/43741131-35b097f4-9982-11e8-9ddb-d4e057cd0810.png)
^ Here's what happens when I import it now, unsure how to play it but that's just unfamiliarity with Maya.
