### ISSUE TITLE
Bfres Dae export bone positions incorrect

### ISSUE THREAD

**Issue by Makiah** [jam1garner/Smash-Forge#240]
Currently the bear model appears as follows via Smash Forge exported DAE: 
![image](https://user-images.githubusercontent.com/10727824/43725638-ef7da310-9951-11e8-95dd-7d114eb5183e.png)

RTB's MAXScript seems to have better results: 
![image](https://user-images.githubusercontent.com/10727824/43725734-2a940688-9952-11e8-8f19-43d72bb09eda.png)

Here's a [mirror to RTB's script](https://github.com/Makiah/BotW-SBFRES-to-FBX/blob/master/fbxextraction/Libraries/WiiU-Switch_BFRESImporter_R6.85_06_20_18/BFRES%20Script_R6.85.ms) (he's hosted his work on the VG Resource, I'll see if I can find the link), it might be useful to deciphering bone weights in this tool.

**Comment by ScanMountGoat** [comment]
fixed in latest PR
