### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by AlexClimax** [jam1garner/Smash-Forge#25]
Hello, I've been attempting to use this tool for a few days now. To no avail.
Everytime I open a file, the program just, Crashes. FITD, FITC or Smash Forge itself.

![crrash](https://cloud.githubusercontent.com/assets/24727666/21447419/0aa51982-c89a-11e6-93e8-f442d5ccbf88.PNG)

I am on Windows 7, 64bit, OpenGL 2.1

**Comment by Demonslayerx8** [comment]
Smash Forge needs OpenGL 3.0 or higher. You need a new GPU to support

**Comment by AlexClimax** [comment]
Well poop. Can't really buy a new compy right now either. Ehhh. alrghty. I though it was something program wise. I kept hearing 1.5 and above was good for whatever reason. Never heard someone say it needed 3.0.

Thank ya thoughh
