### ISSUE TITLE
Switch BFRES render null reference exception

### ISSUE THREAD

**Issue by slashiee** [jam1garner/Smash-Forge#251]
A new issue that has come from only the latest commit 98566483ea30809cef1257e0cdc0e1d0a21a6035. I've tested models from Splatoon 1, Splatoon 2, Smash 4 (just to make sure if the entire program wasn't busted), Mario Kart 8, Super Mario Odyssey and both versions of Breath of the Wild. Only models from Splatoon 2, Super Mario Odyssey and BotW Switch fail to load. My GPU is a NVIDIA GeForce GTX 1060.

Smash 4:
![2018-08-07_23-22-44](https://user-images.githubusercontent.com/15317421/43819913-7e1f7c4a-9a99-11e8-8937-74e78ff25b3c.png)
Mario Kart 8:
![2018-08-07_23-25-49](https://user-images.githubusercontent.com/15317421/43819924-87a20512-9a99-11e8-83a7-f9d45af3650c.png)
Splatoon 1:
![2018-08-07_23-26-09](https://user-images.githubusercontent.com/15317421/43819918-831a27d6-9a99-11e8-820f-c9af87f20a54.png)
Breath of the Wild (Wii U):
![2018-08-07_23-31-22](https://user-images.githubusercontent.com/15317421/43820084-073c895a-9a9a-11e8-8b46-659c01a0d425.png)
Splatoon 2/Super Mario Odyssey/Breath of the Wild (Switch):
![2018-08-07_23-23-15](https://user-images.githubusercontent.com/15317421/43819934-8f5c760c-9a99-11e8-910b-5b38ec4452bd.png)

I don't have Mario Kart 8 Deluxe files dumped so I can't check those and see if they have the same issue. I've checked shader errors logs and it only complained about the point shader.

**Comment by ScanMountGoat** [comment]
Copy paste what appears under details and upload it in a text file.

**Comment by slashiee** [comment]
[error.txt](https://github.com/jam1garner/Smash-Forge/files/2270273/error.txt)

**Comment by ScanMountGoat** [comment]
It seems to be an issue when the OpenGL textures refresh. @KillzXGaming

**Comment by ScanMountGoat** [comment]
Should be fixed now in the latest version.
