### ISSUE TITLE
Models not Visable. Stage texture issues

### ISSUE THREAD

**Issue by Anamalgam** [jam1garner/Smash-Forge#28]
I tried to open up the model for palutena so I could do some studying, but when i opened it up, the only thing that was visable was the bones. I checked the mesh list, render settings, textures and everything. Everything was in order there but still no model visable still. also the open character command just cause something called FITD to crash.

As far as stages go. the stages load, but most of the textures dont. For instance in windy hill omega. the back islands are fully textured. however everything else isnt. but the normals are there and the stage data like spawns and stuff.

I dont remember the exact number for my OpenGL but i think its about 3.1
And below is the system information.

OpenGL might be the issue however as If i activate it in cinema 4d, everything turns black as well
(https://cloud.githubusercontent.com/assets/24865110/21582611/185791dc-d02d-11e6-8487-0853637fa608.png)

**Comment by KillzXGaming** [comment]
Seem to be from regression caused by the latest few PRs. Opening one nud file shows textures, and opening another will then remove the textures from one object and then onto another.

**Comment by Anamalgam** [comment]
so is there a way to fix any of the issues or do i just need a better laptop

**Comment by KillzXGaming** [comment]
Nope try using this build. 
[Smash Forge.zip](https://github.com/jam1garner/Smash-Forge/files/680153/Smash.Forge.zip)

**Comment by Anamalgam** [comment]
Stages work! still no character models however

**Comment by KillzXGaming** [comment]
If it's a character make sure the model.vbn is present.

**Comment by Anamalgam** [comment]
it is

**Comment by Escope12** [comment]
I had the same problem too.

**Comment by Ploaj** [comment]
That's interesting that stages will render by characters won't - they use the same rendering code.
Try maybe lowering the rendering fps? It's that "60" on the viewport.

**Comment by revel8n** [comment]
Some other things to check from what i ran into during my recent changes to Melee format support:
- Check that the number of bones in the model is less than the number specified in the vertex shader
- Ensure vertex shader and resulting shader program were able to compile and link successfully

Unfortunately i do not have any Smash 4 assets to check this, but this was the issue for me with Melee DAT files on some machines.
