### ISSUE TITLE
NUD shader program validation error for AMD

### ISSUE THREAD

**Issue by Demonslayerx8** [jam1garner/Smash-Forge#298]
![image](https://user-images.githubusercontent.com/17195757/45454383-82c47f00-b698-11e8-96d0-b4180b423baa.png)

**Comment by ScanMountGoat** [comment]
[Nud_Error_Log.txt](https://github.com/jam1garner/Smash-Forge/files/2377002/Nud_Error_Log.txt)
*Program Errors:
Validation failed! - Different sampler types for same sample texture unit in fragment shader.*

**Comment by ScanMountGoat** [comment]
``` csharp
// In NUD.cs
System.Diagnostics.Debug.WriteLine(shader.ValidateStatusIsOk); // Always prints false for NUDs
p.renderMesh.Draw(shader, camera);
```

**Comment by ScanMountGoat** [comment]
Fixed in the latest update.
