### ISSUE TITLE
GUI too small on high DPI displays

### ISSUE THREAD

**Issue by NWPlayer123** [jam1garner/Smash-Forge#299]
Somewhere between https://github.com/jam1garner/Smash-Forge/commit/1cd5f3116d75495197477ddfdce2e17d3f4e522b / https://github.com/jam1garner/Smash-Forge/commit/de99d2878ec06a2e8f4725ec55549e6fafc6c61a,
Smash Forge on my 4K display majorly broke (which is what always happens when programs are "DPI aware" which makes them very tiny)
![screenshot_272](https://user-images.githubusercontent.com/3280345/45529781-38c8bf80-b7a4-11e8-929e-80e6ac4daaf5.png)

**Comment by ScanMountGoat** [comment]
You can use an external manifest as described in this [tutorial](https://appuals.com/disable-display-scaling-on-high-dpi-devices-in-windows-10/). It was affected by an unrelated change, so it isn't worth looking into at the moment.

**Comment by NWPlayer123** [comment]
That worked, thanks @ScanMountGoat
