### ISSUE TITLE
Some animations not playing properly

### ISSUE THREAD

**Issue by Escope12** [jam1garner/Smash-Forge#3]
Some of the animation omo files are not playing properly. Can you guys fix this so that I can extract them properly?

**Comment by Y2K-x** [comment]
We can't identify the problem if you do not provide us with screenshots or GIFs of the exact problem you are encountering. Please provide us with some screenshots of your issue so we can get to the bottom of what is happening. Thank you.

**Comment by Escope12** [comment]
Here is one screenshot that proves the issue. https://imgur.com/gallery/JNbzc

**Comment by Escope12** [comment]
![2016-10-13_15-38-59](https://cloud.githubusercontent.com/assets/8963276/19364663/14a2005e-915d-11e6-9967-5b8d3c27cb79.gif)
![2016-10-13_15-47-09](https://cloud.githubusercontent.com/assets/8963276/19364664/14a5d7e2-915d-11e6-95f4-193dc4bd25bd.gif)
Here is my evidence of the problem. I hope you guys can fix this so that I can get the exact animation that I need.

**Comment by Sammi-Husky** [comment]
What is this from? A stage? What stage if so? It's hard to debug things when we don't know what were looking at. If you could, please upload the sample vbn and animations

**Comment by jam1garner** [comment]
"XDolpic" is Delfino I believe

**Comment by Escope12** [comment]
Here is the file

**Comment by Sammi-Husky** [comment]
Looks like you uploaded the entire stage folder for delfino, but what .nud and .vbn are you opening?

**Comment by Escope12** [comment]
I'm opening the .vbn from dyr_Z_XDolpic_Chikei_set and the one from dyr_Z_XDolpic_KamomeA_set and one from dyr_Z_XDolpic_Suimen_set. I also tried the ones in the stage/melee/XDolpic folder.

**Comment by Escope12** [comment]
Will this issue be fixed in the next build?

**Comment by Escope12** [comment]
@Sammi-Husky @Y2K-x Will this issue be fixed in the next build?

**Comment by Sammi-Husky** [comment]
Honestly, no idea yet. None of us have had time to look into the issue yet. We'll get around to it when we can. Other than that, i can't give you any estimate sorry

**Comment by Escope12** [comment]
@Sammi-Husky Okay so for now I'll have to wait.

**Comment by Escope12** [comment]
Can we keep this issue opened?

**Comment by Escope12** [comment]
@jam1garner Will this issue also be fixed in the new version as well?

**Comment by Escope12** [comment]
![2016-11-10_17-11-27](https://cloud.githubusercontent.com/assets/8963276/20199188/dae00016-a776-11e6-88a9-825d3df393d2.gif)

**Comment by Escope12** [comment]
It's all of the stages that their bones don't move when I play their animations.

**Comment by Demonslayerx8** [comment]
every single stage animations play for me, only a few from delfino plaza doesnt, and the windmills from woolly world

it might be cause of the nud coding being updated for DAE imports, dunno. Thats something for @Ploaj to look into.

**Comment by Escope12** [comment]
I also tested out Halberd and their animations but their animations didn't play properly either.
