### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by Supershyguy** [jam1garner/Smash-Forge#30]
I've been making a villager mod where the only thing I changed was I imported a different hairstyle from a different game and put it on villager. I exported it to noesis and then exported it again as dae. I then went to smash forge and did what I needed to do in order to be able to save it as nud. Now normally it would work, however instead I got this error: https://github.com/jam1garner/Smash-Forge/issues/20. I did the same process with one of the regular in game villagers and I still got the error. I tried this with other regular in game models from different characters to see if the error message would appear and it didn't. For some reason villager will not work. If I need to be more specific I made a really big thread that you can find here: http://gamebanana.com/threads/206088.

**Comment by Ploaj** [comment]
It would be useful to have one of the files that don't work so we can check manually to see what's wrong.

**Comment by Supershyguy** [comment]
@Ploaj Oh my. Sorry for the late response. Here's the file: https://www.dropbox.com/s/4po9qtf0jy0qon6/Model.zip?dl=0
I also added the model.vbn file just in case.
