### ISSUE TITLE
Viewport issue with hiding meshes

### ISSUE THREAD

**Issue by Demonslayerx8** [jam1garner/Smash-Forge#321]
Unchecking meshes in the model list to hide them does nothing in the viewport until you move the camera, or click in the viewport, same thing with Reset Camera, won't do nothing. First noticed in commit [87d9cccda35ab6bf6101b8e6673e96f6da83225b](https://github.com/jam1garner/Smash-Forge/commit/87d9cccda35ab6bf6101b8e6673e96f6da83225b)

**Comment by Demonslayerx8** [comment]
It's still an ongoing issue, pretty much with anything being enabled/disabled with options in Render Settings.

**Comment by ScanMountGoat** [comment]
All of the listed problems were fixed. Please submit new issues instead of resurrecting old, unrelated issues.
