### ISSUE TITLE
Viewport bug issue's

### ISSUE THREAD

**Issue by Demonslayerx8** [jam1garner/Smash-Forge#322]
As the last issue that I opened, options in Render Settings doesn't take effect until viewport is clicked/moved.

**Comment by Demonslayerx8** [comment]
oh and 1 more thing before I actually forget to say this and would have to make another open issue, selecting a bone from the VBN list doesn't show what bone is selected unless viewport is clicked.

**Comment by ScanMountGoat** [comment]
Please post unrelated problems as separate issues.
