### ISSUE TITLE
Render Settings glitches when window not selected

### ISSUE THREAD

**Issue by Demonslayerx8** [jam1garner/Smash-Forge#329]
By changing the render type with the main forge window selected, and having the render setting window not in use, and scrolling through the render options (which is updated in model viewport due to it being selected), makes the window glitch out, fixes itself when window is selected tho. Can be done via scroll wheel with mouse hovering over shading modes.

![image](https://user-images.githubusercontent.com/17195757/46927276-68f4bf80-cfe9-11e8-99e2-7f49ce37ee24.png)
![image](https://user-images.githubusercontent.com/17195757/46927386-ff28e580-cfe9-11e8-85c5-901b0de679fd.png)

**Comment by ScanMountGoat** [comment]
Fixed on latest.
