### ISSUE TITLE
Model Viewer doesn't load

### ISSUE THREAD

**Issue by VideoGamePlayer7** [jam1garner/Smash-Forge#332]
When I import a file in Smash Forge, the model viewer doesn't show up. Can anyone help?

**Comment by ScanMountGoat** [comment]
You need to be more specific about what file you were trying to open.

**Comment by VideoGamePlayer7** [comment]
Wait, I downloaded the source code with the .sln file. My bad XD

**Comment by VideoGamePlayer7** [comment]
OK, I downloaded the release, and I opened a .bfres file, but the model viewer still does not appear. I made sure that the .zip file was unblocked when I downloaded it.

**Comment by ScanMountGoat** [comment]
You need support for OpenGL 3.30 or later.
