### ISSUE TITLE
SDL2 Error on Startup

### ISSUE THREAD

**Issue by ecumber** [jam1garner/Smash-Forge#340]
The program starts and immediately throws an error with "SDL_GL_GetCurrentContext" from SDL2.dll

[log.txt](https://github.com/jam1garner/Smash-Forge/files/2725970/log.txt)

**Comment by ScanMountGoat** [comment]
Does your computer meet the minimum system requirements?

**Comment by ecumber** [comment]
I have a gtx 1060 so i believe so.

**Comment by ScanMountGoat** [comment]
You're running the program on Windows with the latest graphics drivers installed?

**Comment by ecumber** [comment]
I'm running windows 10, gtx 1060, 16gb of ram, ryzen 7 cpu, and the graphics driver dates to 10/2/2018.

**Comment by legoj15** [comment]
I just recently began receiving this error upon boot too. It wasn't always like this, I think it occurred after a GTX driver update some time ago.

**Comment by legoj15** [comment]
So I installed the latest GTX driver some time ago, and downloaded the latest Smash Forge, and I no longer receive an SDL error and can load files again.

**Comment by ecumber** [comment]
I just tried to reopen the newest smash forge commit and it still doesn't work, same error. I was using an older version because that worked but it doesn't export models correctly and I wanted to export something.

**Comment by legoj15** [comment]
So I had the exact same thing happen to me again: I installed a new GPU driver, opening smash forge worked flawlessly, but it crashed, and upon trying to reopen it, I got the SDL error and opening anything crashes Smash Forge

**Comment by ScanMountGoat** [comment]
It's not possible to fix driver related compatibility issues on hardware I don't own.

**Comment by ScanMountGoat** [comment]
This should be fixed on the latest commit. If not, feel free to reopen this issue or open a new issue.

**Comment by legoj15** [comment]
Working for me so far!
