### ISSUE TITLE
Material Editor Crash

### ISSUE THREAD

**Issue by R3564** [jam1garner/Smash-Forge#341]
it's my first time using smash forge but when i go to material editor crashes after seconds and all my work is gone, did i do something wrong?

**Comment by ScanMountGoat** [comment]
Does your graphics card or integrated graphics meet the minimum system requirements?

**Comment by R3564** [comment]
what are the system requirements? how do i find it out?

**Comment by ScanMountGoat** [comment]
https://github.com/jam1garner/Smash-Forge/wiki/Rendering-Issues

**Comment by R3564** [comment]
i'm glsl 1.40

**Comment by R3564** [comment]
damn, i can't buy another computer, i worked so much on mario sport's mix peach...

**Comment by ScanMountGoat** [comment]
We can't support versions any lower than 3.30, so I'm going to close this.
