### ISSUE TITLE
If a BFRES has too many animations, not all of them are loaded.

### ISSUE THREAD

**Issue by ghost** [jam1garner/Smash-Forge#346]
An example of this is MarioAnimation.bfres from Super Mario 3D World. Smash Forge just stops loading in the animations without finishing.

https://ufile.io/u5xze

**Comment by ScanMountGoat** [comment]
The nodes are read but not added properly in the following lines. This should be easy to fix later. Nodes past 1000 aren't added to the UI. 

https://github.com/jam1garner/Smash-Forge/blob/876b91b3ea7d1f97798e8d63c039ecec675a1644/Smash%20Forge/Filetypes/BFRES/Switch/FSKA.cs#L113-L132

**Comment by KillzXGaming** [comment]
It was pretty badly hacked in tbh, it would be better to load them all into one folder though i did have lag issues from that despite other tools working fine with 1000+ nodes at once (anims would play slower). I'll PR a quick fix later today.
