### ISSUE TITLE
Generating nud tangents/bitangents doesn't update model

### ISSUE THREAD

**Issue by Demonslayerx8** [jam1garner/Smash-Forge#355]
Importing a DAE into forge does not generate tangents/bitangents at all, neither does right clicking the NUD to generate Tan/Bitan.

**Comment by ScanMountGoat** [comment]
There are two potentially unrelated issues to be fixed.
- [ ] No update after saving: 8c6f2de3457e75679f08080da41335b9d250de52
- [ ] Models invisible after generating: 223fb0d648c3be7ff1be9213725c41c1e235e44b
