### ISSUE TITLE
Frequent System.OutOfMemory exceptions.

### ISSUE THREAD

**Issue by SubsonicBeatz154** [jam1garner/Smash-Forge#358]
This bug is really starting to get on my nerves... I have 16GB of RAM, i shouldn't be actually running out of memory. I'll either get a System.OutOfMemory exception, or the application will just crash. It just happens out of nowhere at random. I can't even work on my model import i'm currently doing because the application doesn't want to freaking work. This started happening recently, everything was fine in builds from a couple months ago.

**Comment by ScanMountGoat** [comment]
"doesn't want to freaking work" sounds like it might be a bug. What were you doing when the exception happened?

**Comment by SubsonicBeatz154** [comment]
There isn't anything in particular that seems to trigger it, it just happens at random.

![image](https://user-images.githubusercontent.com/43527795/70293777-61751480-17af-11ea-9a4a-075ac0afb887.png)

**Comment by SubsonicBeatz154** [comment]
But it usually happens after just a minute or two of work.

**Comment by SubsonicBeatz154** [comment]
I'm working with Smash 4 models, just thought i should throw that in there.

**Comment by ScanMountGoat** [comment]
What GPU do you have?

**Comment by SubsonicBeatz154** [comment]
AMD Radeon RX 570. Like i said, everything worked fine a couple months ago, but i'm using this for the first time in months, and now this is happening.

**Comment by SubsonicBeatz154** [comment]
From my testing, this seems to happen the most when working on materials.

**Comment by SubsonicBeatz154** [comment]
Now i see what's going on, there is a memory-leak. Once it hits around this amount is when i get the System.OutOfMemory Exception.

![image](https://user-images.githubusercontent.com/43527795/70295222-380ab780-17b4-11ea-86d6-de73d92e9b2e.png)

**Comment by Demonslayerx8** [comment]
I'm not getting any memory leaks at all on my end, besides a high CPU percentage, and very high power usage, and yes, this is the latest version of forge with it's buggy af GUI lol
![image](https://user-images.githubusercontent.com/17195757/70295672-b52a3280-179c-11ea-9c23-5e3be014a176.png)

**Comment by SubsonicBeatz154** [comment]
From further testing, i can confirm opening the material editing window is what triggers the memory leak.

**Comment by SubsonicBeatz154** [comment]
OK, now this is weird. I deleted the application and downloaded a fresh copy, and the problem seems to be gone now.

**Comment by ScanMountGoat** [comment]
Did you have any custom material presets?

**Comment by SubsonicBeatz154** [comment]
No.
