### ISSUE TITLE
Default Jigglypuff bone SWG_CapJc__swing causes .DAE's to fail saving as .NUD

### ISSUE THREAD

**Issue by SupremeDevice** [jam1garner/Smash-Forge#36]
-EDIT-
I have narrowed down this error when saving a c00 jigg's .dae as a .nud as an issue with the bone SWG_CapJc__swing. 
![what](https://cloud.githubusercontent.com/assets/23326854/22575331/79cedac2-e97a-11e6-9549-f9539fb72108.png)

-EDIT 2-
Nevermind, apparently while I was able to get this to work before changing nothing from the steps that I did I'm getting that same error again.

Removing this bone on c00 Jigglypuff will cause saving to work correctly. From the quick test I did on c01 and c03 Jiggs, saving as .NUD will work perfectly fine with them without any removal of bones necessary.

------
In my original issue, while Smash Forge created .DAE's originally were too small, they no longer appear that way as far as I can tell.

**Comment by InTheBeef** [comment]
Got (the same?)the scale issue with importing Zero Suit from 3DS Max (vbn first, noesis dae). 
![image](https://cloud.githubusercontent.com/assets/25026032/22267550/15034268-e27c-11e6-948b-2be833d8bdf8.png)

**Comment by SupremeDevice** [comment]
Apparently, as of the current build (just implemented SWAG bones), you can't even save Jigglypuff's .DAE as a .NUD, even if no modifications were done (besides running through Noesis. )

I made sure to double-check and sure enough, you CAN save Jigg's .nud as a .nud just fine, so it's not like her model/bones/whatever is invalid, unless the process of saving a .nud as a .nud is just copy/paste and edit the materials.

Obviously, some information is being lost somewhere in between exporting Jigglypuff's .nud, running through Noesis, reimporting and saving.

**Comment by Ploaj** [comment]
Could you upload the dae in question? The error messages are not very descriptive (^ ^')

**Comment by SupremeDevice** [comment]
The .DAE in question was just c00 jigglypuff saved to .dae and reimported, it would fail to save with that error. Trying this process in recent builds won't even let me import the c00 .dae whether using Noesis or not. Using the .dae straight from Forge just crashes, and the one from Noesis give the error "Object reference not set to an instance of an object."

**Comment by Ploaj** [comment]
This should be fixed now
