### ISSUE TITLE
Broken animation export for Pokken Tournament

### ISSUE THREAD

**Issue by wood5578** [jam1garner/Smash-Forge#365]
I loaded up some animation from Pokken Torunament and it plays fine in Smash Forge but when I tried to exporting it into Maya .anim the animations were broken with only a few bones working.

### Attachments 
[Models and Animation](https://github.com/jam1garner/Smash-Forge/files/4462397/Models-Anims-etc.zip)
[GIFs showing the animation in Smash Forge and Maya](https://github.com/jam1garner/Smash-Forge/files/4462400/Renders.zip)

**Comment by KnowdiceWasTaken** [comment]
I have this exact same problem. please fix animation exports!

**Comment by future-doghnut** [comment]
I get this issue too. Can someone Please address it? DAEs Export fine but animations only seem to export the start of bone chains. 
For example, Lucario went from this:
![Render](https://user-images.githubusercontent.com/80102183/110107077-605fd800-7da2-11eb-85de-45d39841a09e.gif)
To this:
![Blender  D__Games_Yuzu_Pokkèn Tournament DX_Decompiled Assets_(p448)_Uploadtogit blend  05_03_2021 11_04_15](https://user-images.githubusercontent.com/80102183/110107271-9735ee00-7da2-11eb-9ce8-c4c9c2c81fad.png)
The Bones that do export appear to keep their animation apon being exported.

**Comment by MDTravisYT** [comment]
On my end, I'm exporting these animations as a SMD. Looking into the data, in my case, it is only exporting one bone. 
Additionally, the exported DAE model, while having armature, is not linked up to the actual model.

I'm aware this tool has not been updated in some time, so I hope to find some sort of alternative to export these formats.

![image](https://github.com/jam1garner/Smash-Forge/assets/59547361/1fdbe064-d859-47d5-9fb8-f5d704ece000)

https://github.com/jam1garner/Smash-Forge/assets/59547361/4237de47-8f9a-4db4-b97c-3fdbbc78266b

**Comment by Dr-HyperCake** [comment]
I believe this problem should be fixed as of #379. Until that gets merged, you can instead simply update your `hashTable.csv` file with [the one from my fork](https://github.com/Dr-HyperCake/Smash-Forge/blob/master/Smash%20Forge/hashTable.csv).

**Comment by ScanMountGoat** [comment]
This appears to be fixed by #379

**Comment by Drizz1le** [comment]
> On my end, I'm exporting these animations as a SMD.

I know I'm very late to the party, but how do you export the animations as .SMD? Whenever I unpack the .DRP I just get files with no extension on them. If you could help me at all it would be really appeciated.
