### ISSUE TITLE
Smash Forge crashes when opening Nuds or Nuts (Nvidia)

### ISSUE THREAD

**Issue by SupremeDevice** [jam1garner/Smash-Forge#366]
On the latest current build (Timestamp: 2020-06-04T16:15:19.0000000Z)
Using either 'Open File' or 'Open Stage', SF will spend a second or two trying to load the file and then close itself without any error. Even attempting to load one of CF's vanilla skins, extracted from a freshly downloaded (and thus untouched) dump of the game results in a crash.
Sometimes it won't crash when loading a .nut (but will throw errors about invalid window and then not display the textures properly).

Edit: Apparently this issue has existed for a while according to discord, I just haven't known about it because I haven't messed with this stuff in two years.
![image](https://user-images.githubusercontent.com/23326854/85440870-1d334100-b554-11ea-9f3e-d35f416428fa.png)

**Comment by ScanMountGoat** [comment]
Try the following:
1. Open Smash Forge
2. File > Reload Shaders
3. File > Export Shader Error Logs

If any of the shaders failed to compile, upload the error logs as a zip file. If the application closes without warning, it's probably an issue with OpenGL.

**Comment by SupremeDevice** [comment]
[shader errors.zip](https://github.com/jam1garner/Smash-Forge/files/4821403/shader.errors.zip)
It only complained about the "Point" shader not compiling correctly though.

**Comment by SupremeDevice** [comment]
Sometimes when attempting to open either a .NUD or .NUT, it'll throw up multiple errors about an invalid window. When this happens with a .NUT it'll at least load up the menu correctly, just not display the textures (instead showing a white box with red outline+X). Opening a .NUD, it'll still crash after dismissing the errors. 

Also seems to crash when loading a .DAE with bones. Loading a random model with no bones would spit an error complaining about "Index was outside the bounds of the array" --- but no crash.

Smash Forge can at least open these files correctly : .VMB, .SB, and .MTA. (Of course, none of these use the 3D viewport)

I wish I thought to screenshot the errors when they happened, but they don't appear consistently and thus can't take one now.

**Comment by ScanMountGoat** [comment]
Does the application ever load a nut or nud and then properly display it in the viewport/editor?

**Comment by SupremeDevice** [comment]
No, nuds never load and nuts don't display properly even when they don't crash.

**Comment by ScanMountGoat** [comment]
It seems like something is failing in creating the window's graphic context. This has been a sporadic issue with Nvidia GPUs for a while now. Without hardware to test on (I have AMD and Intel integrated), it's unlikely this will be fixed anytime soon. 

If someone with a recent Nvidia GPU wants to debug the program from visual studio, I may be able to glean some information based on where the application throws an exception. An image or copy pasted text from the error message would also be helpful. I'll leave this issue open in case any new information comes up.

**Comment by SupremeDevice** [comment]
Heyo, got the error to show up! Opened up a .NUD and this happened
![image](https://user-images.githubusercontent.com/23326854/85933713-02d4cc80-b8a0-11ea-8c07-3643f9ef00ad.png)

[smashforge error.txt](https://github.com/jam1garner/Smash-Forge/files/4841397/smashforge.error.txt)

**Comment by SupremeDevice** [comment]
Howdy, swinging by to say that I've tried my hand at compiling smash forge on my own and...
it still doesn't work, lol.

I actually tried compiling the OG vbn editor from 2016 and that actually works like a charm, 3d viewport and all. Too bad it's not very useful now :P

Interestingly, and unfortunately, trying to replace the existing SFGraphics lib files with the latest straight from your repo causes the compilation to fail. I was hoping by some miracle that would fix it, but alas.

I'm not very experienced with Visual Studio/debugging, but since I got it to compile successfully on my own computer, I'm willing to try debugging it for you if you can point me in the right direction.

**Comment by ScanMountGoat** [comment]
You can try debugging Forge in Visual Studio by pressing F5 or clicking the debug icon. It should open the line of code where the exception occurred. "Invalid window" means the OpenGL setup failed. There may be some workarounds online searching for "OpenGL invalid window nvidia".

**Comment by SupremeDevice** [comment]
Okay, I frequently got one of these two errors when attempting to open a .nud file
`System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
`
![image](https://user-images.githubusercontent.com/23326854/100800474-4520ad80-33ec-11eb-8b29-64f7d00ff91b.png)
`OpenTK.Graphics.GraphicsContextException
  HResult=0x80131500
  Message=Invalid window
  Source=OpenTK
  StackTrace:
   at OpenTK.Platform.SDL2.Sdl2GraphicsContext..ctor(GraphicsMode mode, IWindowInfo win, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Platform.SDL2.Sdl2Factory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Sdl2GLControl.CreateContext(Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`
![image](https://user-images.githubusercontent.com/23326854/100801069-16ef9d80-33ed-11eb-93f7-d54484848d3c.png)

Here is the full output log for both cases:
[full error memory access.txt](https://github.com/jam1garner/Smash-Forge/files/5625685/full.error.memory.access.txt)
[full error invalid window.txt](https://github.com/jam1garner/Smash-Forge/files/5625667/full.error.invalid.window.txt)

**Comment by SupremeDevice** [comment]
I tried updating OpenTK to v3.3.2, but unfortunately that didn't seem to fix the issue. Granted, I may not have done so correctly- I ended up downloading the packages from NuGet and replacing the DLLs smash forge came with with the new ones after it failed building the first time, but there may be more that needs to be done.

**Comment by ScanMountGoat** [comment]
It may be possible for me to fix this by adjusting how the graphics context is created. I've found similar issues online. I can't promise any fixes though since I can't reproduce it on my end.

**Comment by ScanMountGoat** [comment]
This seems to be the same as #340

**Comment by ScanMountGoat** [comment]
@SupremeDevice let me know if the latest build is working when you get a chance

**Comment by BleuBleu** [comment]
@ScanMountGoat Hi! I have the same bug on my project (rare opentk context creation crash on some nvidia cards) with no way to repro it as well. :) If you find a solution, please point me to a commit that I can check out! Thanks so much.

**Comment by SupremeDevice** [comment]
The latest build does work for me! Thank you very much!
Hopefully this doesn't break it for anyone else, haha.

**Comment by ScanMountGoat** [comment]
Glad to hear it

**Comment by ScanMountGoat** [comment]
@BleuBleu see the latest commit. I referenced the issue here: https://github.com/mellinoe/ImGui.NET/issues/34#issuecomment-339823953
