### ISSUE TITLE
can't compile smash forge in visual studio

### ISSUE THREAD

**Issue by fisch123456** [jam1garner/Smash-Forge#368]
Hi Fisch here.
I got a problem.
When I want compile Smash forge in visual studio it gives me 18 errors
Can you please help me? 
Thanks.
![eror7](https://user-images.githubusercontent.com/69847532/96347853-c6261e80-10a4-11eb-9926-bbc928864af4.PNG)

**Comment by ScanMountGoat** [comment]
This might be an issue with how you downloaded/extracted the files. I'm closing this as it isn't something we can fix on our end.
The following link may help.
https://stackoverflow.com/questions/51348919/couldnt-process-file-resx-due-to-its-being-in-the-internet-or-restricted-zone-o

**Comment by ScanMountGoat** [comment]
If you just want to run the program, you can download it on the releases tab. 
https://github.com/jam1garner/Smash-Forge/releases

**Comment by fisch123456** [comment]
Hi I did that but after opening nut file from totono it shows me this black sreen.
Also when I tried to move mip level it shows me unhandled exeption error.
![black screen](https://user-images.githubusercontent.com/69847532/96348390-a5f85e80-10a8-11eb-81c2-23875f9053f0.PNG)
![eror4](https://user-images.githubusercontent.com/69847532/96348394-ac86d600-10a8-11eb-9695-c4c8d76e7f03.PNG)

**Comment by ScanMountGoat** [comment]
Please open a separate issue with details about the error. You can upload files in a zip to help reproduce the issue.
