### ISSUE TITLE
UI loads slowly when running under Wine

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [jam1garner/Smash-Forge#374]
the UI is inefficient and takes sometimes upwards of a few minutes to load an element

i'm using wine, but have no issue with other tools like BrawlBox, Switch Toolbox and even Cemu, but i can try it on windows later if it's needed

**Comment by ScanMountGoat** [comment]
Smash Forge is strongly tied to WinForms, which is designed to work on Windows. Smash Forge can theoretically run using Wine or Mono, but we don't make any guarantees about the experience on other platforms. I haven't heard of anyone experiencing this issue on Windows. No one is actively working on this project, but I'd be happy to review any PRs that attempt to fix this.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
well, winforms switch toolbox doesn't have any issues

**Comment by jam1garner** [comment]
> well, winforms switch toolbox doesn't have any issues

That doesn't mean much. We can't really gauge what performance issues will arise on unsupported platforms. I understand this is frustrating (I use Linux and strongly dislike WinForms now) but it's hard to justify putting development effort in for an old project like this. Maybe if you can profile which parts run slow under wine there will be an obvious fix but I can't guarantee we can/will do anything

**Comment by jam1garner** [comment]
To clarify further, Wine has slower implementations for some things and narrowing down what or why is time consuming. Other tools not having this issue means they just don't use whatever feature causes slowdown. We can't really control that
