### ISSUE TITLE
Smash Ultimate Support

### ISSUE THREAD

**Issue by Bibidimah21** [jam1garner/Smash-Forge#378]
Add Super Smash Bros. Ultimate game Support to Smash Forge, become more modern than Smash 4.

**Comment by ScanMountGoat** [comment]
Smash Forge is not being actively maintained, so support for new games will not be added. Smash Ultimate already has its own dedicated libraries and tooling. 

Blender import/export: https://github.com/ssbucarlos/smash-ultimate-blender
Model viewer and editor: https://github.com/ScanMountGoat/ssbh_editor
Texture batch converter: https://github.com/ScanMountGoat/ultimate_tex
Texture converter: https://github.com/KillzXGaming/Switch-Toolbox
