### ISSUE TITLE
Mass Animation Conversion Tool?

### ISSUE THREAD

**Issue by BSC-GoldN** [jam1garner/Smash-Forge#38]
Would it be possible to add something like this as a feature? I have had several situations where I had to port 50+ .anim files to .omo, and it is a complete pain to do them 1-by-1.

-GoldN

**Comment by Ploaj** [comment]
I think you can already open multiple animations at a time and then export them. Maybe export them as pac and then extract them? We should probably add a save pac contents type thing.

**Comment by Ploaj** [comment]
This has been added. Right click "Bone Animations" -> Export all as omo
