### ISSUE TITLE
Certain names are changed in the mesh list

### ISSUE THREAD

**Issue by InTheBeef** [jam1garner/Smash-Forge#41]
Simply, any objects with "chara" or "polyg" in the name have that specific part of the name removed when importing it into Forge.
The only time I have gotten around this was when merging two models together, the name of the object in the .nud being merged with the current model would not have those names removed.

**Comment by InTheBeef** [comment]
"chime" also seems to be affected by this.

**Comment by Ploaj** [comment]
Have you been checking the "remove numbers" option with the import?

**Comment by Ploaj** [comment]
this issue is alleviated by not using the remove numbers option on import and by being able to manually rename meshes
