### ISSUE TITLE
Bone Index Broken (Everything is -1)

### ISSUE THREAD

**Issue by FaptainCalcon** [jam1garner/Smash-Forge#43]
So when I go to open any sort of vbn, the index of any bone shows up as -1.
![image](https://cloud.githubusercontent.com/assets/20349893/22534850/48e45368-e8b4-11e6-95e5-fbc782045047.png)

**Comment by SupremeDevice** [comment]
This happens before you open a .nud as well. I'm not sure if this applies to every character, but I know Jigglypuff and Captain Falcon will still have some bones that have a -1 index, but it should still be editable

**Comment by FaptainCalcon** [comment]
I'm opening a nud alongside the vbn. The index still shows up as -1.
