### ISSUE TITLE
After importing .nud, when importing a .dae, .nud model will be removed.

### ISSUE THREAD

**Issue by InTheBeef** [jam1garner/Smash-Forge#47]
As stated in the title, after I have opened a .nud in forge (vbn included), if I then import a .dae (from noesis) the .nud's "Model 0" is replaced with the .dae's "Model 0". This is using the latest commit with a fresh startup of forge, it does not occur if you import the .dae first and .nud after.

**Comment by Ploaj** [comment]
I'm going to close this because I believe it is no longer an issue.
