### ISSUE TITLE
Skeleton is removed on 2nd Model delete

### ISSUE THREAD

**Issue by InTheBeef** [jam1garner/Smash-Forge#52]
When deleting the "Model 0" a second time, the .vbn/skeleton is also removed (resulting in needing to grab the .vbn again after). Unsure if this only applies to .dae imports or all models.

**Comment by struz** [comment]
This is currently intentional. What is your use case for wanting to move from working on the mesh to the bones? In the current version if you just want to hide the mesh you can untick the box on the model.

**Comment by Ploaj** [comment]
I'm going to close this because I believe this is no longer an issue.
