### ISSUE TITLE
 cell-shaded model without using cell-shade preset

### ISSUE THREAD

**Issue by FaptainCalcon** [jam1garner/Smash-Forge#54]
not sure if i'm doing something wrong or not, i used the regular character mat presets on a model i merged with cloud's model and the entire model comes out cell shaded

**Comment by Ploaj** [comment]
What do you mean by cell shaded? Can you put a screenshot?

**Comment by FaptainCalcon** [comment]
http://files.gamebanana.com/img/ss/skins/58a89c583f941.jpg

**Comment by FaptainCalcon** [comment]
![20170218120025](https://cloud.githubusercontent.com/assets/20349893/23105816/82e23e9e-f6a2-11e6-950a-d9348ce4f869.jpg)
