### ISSUE TITLE
Screwed Up Bones on .DAT File

### ISSUE THREAD

**Issue by lemurboy12** [jam1garner/Smash-Forge#65]
I know this isn't the program's main purpose or priority, but since it reads Melee .DAT files, Mario Kart Arcade GP 2 surprisingly uses the same format and almost works. However, any rigged model shows up like this.

http://puu.sh/vi9Kr.jpg

If samples are needed, here are a few.
http://puu.sh/vi9Ve.zip

**Comment by Ploaj** [comment]
Wow, they are more similar than I expected.

I think I see the difference, but I don't see a way to detect it when reading the files. For now you can open the DAT.cs file and find these lines and delete them then rebuild.
`if (v.bones.Count == 1)
                {
                    v.pos = Vector3.Transform(v.pos, mt);
                    v.nrm = TransformNormal(mt, v.nrm);
                }
                // scale it
                v.pos = Vector3.Multiply(v.pos, stageScale);`

http://i.imgur.com/f3KSF6R.png

No idea what's up with the bones though,
