### ISSUE TITLE
Jigglypuff hitbox displacement exaggerated by bone stretching

### ISSUE THREAD

**Issue by Ben-Arthur** [jam1garner/Smash-Forge#75]
It seems Jigglypuff's hitbox placement (Uair, Ftilt, Dtilt, and possibly Utilt) is getting thrown off by the bone stretching. Distance between the hitboxes gets exaggerated in the direction that it stretches. I think this may be related to the recent commit which showed hurtboxes change in shape based on how their bone stretched. I can't tell if this only affects specific bones (or only her character, for that matter), because I haven't tried enough moves with several hitboxes attached to a stretched bone. Apologies if there isn't too much information to go off of there.
Here's a picture of dtilt I took in the program yesterday (May 31, 1:31 PM EST)
![dtiltcrop](https://cloud.githubusercontent.com/assets/22332781/26700399/358a7e42-46eb-11e7-8885-adc6ebba08a0.png)
And here's a picture I took just now
![hitboxissue](https://cloud.githubusercontent.com/assets/22332781/26700811/d1a78f44-46ec-11e7-8405-147879d719a1.png)
None of Jigglypuff's files have been altered, and I'm using the current version as of right now (June 1, 5:08 PM EST)

**Comment by Ploaj** [comment]
I was working on fixing extended hitboxes transparency and forgot to change those back. Should be fixed now
