### ISSUE TITLE
Marth's hitboxes skewed strangely.

### ISSUE THREAD

**Issue by FamilyTeamYT** [jam1garner/Smash-Forge#76]
When looking at Marth's hitboxes through Smash Forge, somehow, Marth's sword is bent at a much sharper angle than normal and his hitboxes follow through.
![f10mar](https://cloud.githubusercontent.com/assets/29163606/26754504/709ecafc-4852-11e7-9b33-959bee5648c1.png)
![f11mar](https://cloud.githubusercontent.com/assets/29163606/26754503/7098ffbe-4852-11e7-904a-186751e9db48.png)
![f12mar](https://cloud.githubusercontent.com/assets/29163606/26754505/70a324e4-4852-11e7-9df6-2823979a3976.png)
For reference, [this video showing a visualization of his hitboxes shows them completely differently](https://www.youtube.com/watch?v=WnDdIIcAsq8). This problem doesn't seem to happen when viewing Lucina's hitboxes.
![f12luci](https://cloud.githubusercontent.com/assets/29163606/26754523/d0e22c7e-4852-11e7-8520-21103524f5ef.png)

**Comment by Ploaj** [comment]
Are you opening all the animation pacs?

**Comment by FamilyTeamYT** [comment]
It seems that has fixed the issue. Thank you.
However, I do find it strange Lucina doesn't seem to do this at all.

**Comment by struz** [comment]
You can use file>open>open character in the menu to open the base folder for a character (e.g. fighter/Marth) and it will automatically open all the relevant model, animation and script files. Some fighters just have more animation files than others.
