### ISSUE TITLE
Exeption occurs when trying to change the values of a .vbn file

### ISSUE THREAD

**Issue by Xiquelo** [jam1garner/Smash-Forge#78]
I don't know if it's just me, but Smash Forge launches an exception when trying to change a .vbn file values. For example when trying to change the X or Y values of a bone platform.
Am I doing something wrong?

Also it would be convenient to be able to view all the bones that are in a stage when importing to Smash Forge. I notice that in the program those options are visible, but nothing appears when importing a whole stage.
Please some body help me with this, I will appreciate it.

**Comment by Ploaj** [comment]
Fixed the crash.

All the bones for opened models should be visible in the main viewport. Make sure render bones is checked in render settings.
