### ISSUE TITLE
MDL0 opens on its back, breaks on export (game softlocks)

### ISSUE THREAD

**Issue by TabuuForteAkugun** [jam1garner/Smash-Forge#8]
A VBN normally imports standing up perfectly straight, like the Mario one (I used that to test)

When I import MDL0, it lays flat on its back with broken bone positions and exports a broken file that won't load in-game. I'm pretty sure that's not supposed to happen.

Lord Fredrik mod:
![screenshot 717](https://cloud.githubusercontent.com/assets/22761617/19360844/308e7518-914e-11e6-82a5-615c1ee853ff.png)

Compared to Ike, the base character.
![screenshot 718](https://cloud.githubusercontent.com/assets/22761617/19360884/5de958d4-914e-11e6-81d8-94829217782f.png)

**Comment by Ploaj** [comment]
Could you provide the mdl0? 

And a heads up, although you can import skeletons and save as vbn for characters, the new skeleton may not work in-game. This is because some things are indexed by bone indices and will break if those bones either aren't there or are not in the format it expects.

**Comment by TabuuForteAkugun** [comment]
Yes I could. Let me zip it for ya,

[LordFredrik_MDL0.zip](https://github.com/jam1garner/Smash-4-Bone-Animator/files/531291/LordFredrik_MDL0.zip)

**Comment by Ploaj** [comment]
The import is correct. Check that mdl0 in brawl box and you'll see it's laying down http://i.imgur.com/C8wqMm8.png

**Comment by TabuuForteAkugun** [comment]
I know. But is ir supposed to import on its back in SAT also when vanilla VBN  don't?

**Comment by Ploaj** [comment]
Yes, it is expected to import on its back if that's how it is in the actual model.

I'm not sure about the broken bones.

**Comment by TabuuForteAkugun** [comment]
So then theres no way to pin down why the game crashes on it.

**Comment by Ploaj** [comment]
There was a bug that has been present since very early on that was just fixed. It should fix bone saving/creation issues.
