### ISSUE TITLE
Hitboxes not being displayed on frame 0

### ISSUE THREAD

**Issue by Ben-Arthur** [jam1garner/Smash-Forge#80]
Currently using the updated version as of June 4th, 2017, 3:20 PM. This is something simple I've noticed with Pikachu, Zero Suit Samus, Little Mac, and it probably applies to other characters as well. For instance, ZSS's and Little Mac's jab1 have an active hitbox only on the first frame, so they fail to show up at all in the visualizer. Pikachu has a few frame 0 hitboxes (down special hit, landing dair/bair), and the hitboxes show up on every correct frame except the first. I haven't modded any files, of course.
EDIT: Here's a picture, if it matters:
![littlemacjabissue](https://cloud.githubusercontent.com/assets/22332781/26765037/473afa60-4941-11e7-9503-f37f696cc686.png)
Also, another commit seems to have been added right before I wrote this, so at the very least this is about the version right before that.

**Comment by rubendal** [comment]
Fixed

![zss-jab-1](https://user-images.githubusercontent.com/10661132/26854075-2e3a9cec-4ada-11e7-900e-73409299345d.png)

On processScript() halt was initialized on 0 which made the while loop get ignored so it didn't process any frame 1 commands
