### ISSUE TITLE
Hitbox interpolation is broken

### ISSUE THREAD

**Issue by Filumbitu** [jam1garner/Smash-Forge#82]
Using commit ddfd358.
Hitbox interpolation seems to default to the TransN bone, and when viewing an animation frame by frame disappear immediatly.
![smash forge_2017-06-07_01-19-15](https://user-images.githubusercontent.com/17123092/26856240-f6dcae54-4b22-11e7-8a48-d1fb16f6a662.png)
![image](https://user-images.githubusercontent.com/17123092/26856355-6a6b2bde-4b23-11e7-9ad1-e428d8d04c71.png)

**Comment by rubendal** [comment]
Fixed, I tried to make game script get processed on handleACMD for frame 1 hitboxes but it caused double execution of the hitbox interpolation, solved by processing script on animation change event
