### ISSUE TITLE
Importing exported .anim file to Maya fails

### ISSUE THREAD

**Issue by gosaints70** [jam1garner/Smash-Forge#85]
When I try to export animations (first tested with Captain Falcon's dash animation) to Maya after exporting it as a .anim file Maya throws two errors saying "Error: Nothing is selected for anim curve import." and "Error: line 0: Error reading file." Is this a problem with the tool or is it an issue with Maya and how can I solve it?

**Comment by StreakThunderstorm** [comment]
I found that you have to first select the TransN joint, select hierarchy and then import the .anim file. I can't seem to get the combined .anim giles that includes all of the body and hand animations together. Its kind of annoying having to export all of the animations separately (Unless I'm doing it wrong.)

**Comment by LAOMUSIC** [comment]
Hi!

ome common reasons and potential solutions for this issue:
1. File Format Compatibility

    Reason: .anim files need to be in a proper format and structure that Maya can interpret. If the .anim file was generated from another software or tool, there might be some incompatibilities in the format that Maya cannot interpret.
    Solution: Ensure that the .anim file is generated from a Maya-compatible source. If you're exporting from another software, try using an intermediate format such as FBX or Alembic, which are better supported across different software.

2. Corrupted File

    Reason: The .anim file might be corrupted or contain invalid data.
    Solution: Open the .anim file in a text editor and check for any signs of corruption, like incomplete data or unusual characters. Maya .anim files should have a readable structure that includes keyframes, time markers, and associated data. If the file looks incomplete or corrupted, try exporting it again.

3. Version Mismatch

    Reason: There could be a mismatch between the version of Maya used to export the .anim file and the version trying to import it. Maya files are often not backward-compatible, meaning that older versions of Maya may not read files created by newer versions.
    Solution: Check the version of Maya used for export and import. If possible, use the same version of Maya for both tasks. Alternatively, update Maya to a newer version to ensure compatibility.

4. Invalid Paths or Settings

    Reason: Sometimes Maya has issues with file paths that contain special characters, spaces, or non-English characters.
    Solution: Move your .anim file to a simple directory path (e.g., C:\temp\) and try importing it again. Ensure that there are no unusual characters in the file name or path.

5. Plugin or Script Conflicts

    Reason: If you are using custom scripts or plugins, they may be causing the issue during the import process.
    Solution: Try disabling or unloading any custom scripts or plugins in Maya that may interfere with the import process. Start Maya in "vanilla" mode without plugins and try importing the .anim file again.

6. Check Animation Preferences

    Reason: Maya’s preferences might be configured in a way that conflicts with the import of .anim files.

    Solution: Reset your Maya preferences to their default state. You can do this by renaming or deleting the preferences folder. After resetting preferences, try importing the file again.

    To reset Maya preferences:
        Locate your Maya preferences folder. It's usually located at:
            Windows: C:\Users\<YourUser>\Documents\maya\<version>\prefs
            macOS: ~/Documents/maya/<version>/prefs
        Rename the prefs folder to something like prefs_backup.
        Restart Maya, and it will generate new preferences. Then try importing the .anim file again.

7. Check for Additional Errors

    Reason: There could be additional underlying errors that are not visible in the basic error message.
    Solution: Open Maya's Script Editor (Window > General Editors > Script Editor) and check for more detailed error messages. This may give you more insight into what exactly is causing the issue.

8. Re-export the .anim File

    Reason: If the file was exported incorrectly, it may contain incomplete or invalid data.
    Solution: Try exporting the animation again and ensure all settings during export are correctly configured. If the problem persists, try exporting using a different format and convert it back to .anim if necessary.
    
    Hope this helps others too!
    
    LAO
