### ISSUE TITLE
Kirby's CatchTurn.omo animation not playing properly

### ISSUE THREAD

**Issue by meleewalugi** [jam1garner/Smash-Forge#87]
Kirby's model and animation is screwed up for CatchTurn.omo.
![forgeproblem](https://user-images.githubusercontent.com/30395098/28552124-86717dd0-70ba-11e7-8e06-b1fcad1cd233.PNG)

**Comment by Ploaj** [comment]
This has been fixed. It was caused by a previously unknown rotation type.
