### ISSUE TITLE
Unanimated joints in some animations.

### ISSUE THREAD

**Issue by tateplayer** [jam1garner/Smash-Forge#92]
hiya, i've been poking around a bit and working on porting some animations into maya via smash forge.

however, the set of animations i'm after seems to have some issues...

https://i.gyazo.com/b206d6d82bc1f034112dd923a9f1e984.gif

if you look at that animation, the end fingers seem to lack animation data. you can especially see it near the end of the gif when he clenches his fingers. this confuses me quite a bit, because they clearly have full animation inside of Smash 4.

however, in some other animations, the bones **do** get animated. i'm wondering if there's a name mismatch between these sets of animations?

https://i.gyazo.com/f7eddf2f492c0c105da4a1d7aadcd091.png

i checked one of the unanimated joints in the .omo files (Middle2N), and the hash exists (3BB120C6) but i'm not sure if that means anything--aside from that the bones exist in the omo.

here's the VBN and here's the NUD:
https://cdn.discordapp.com/attachments/169922403273539584/343817473411252224/model.nud

here's an animation without the working end fingers:
https://cdn.discordapp.com/attachments/169922403273539584/343817868091064331/EnmMasterhandBodyMainWait.omo

the animation joints are even unkeyed in Maya, so i'm wondering where the issue is happening.

here's an animation with the working fingers:
https://cdn.discordapp.com/attachments/169922403273539584/343818042716848128/EnmMasterhandBodyMainYubideppouLoop.omo
https://cdn.discordapp.com/attachments/169922403273539584/343818126833614859/EnmMasterhandBodyMainNigiruLoop.omo

**Comment by TabuuForteAkugun** [comment]
As far as I know some animations have unknown rotation formats, meaning they aren't interpreted properly or at all. A few even infinitely hand Maya on export (Mario's Wait 2).

For animation glitch examples, look at the Waluigi AT's legs, from my memory.

**Comment by tateplayer** [comment]
unknown formats? hm...do you reckon it'd be possible that the ends of the fingers are procedurally animated by using a formula based off of the previous bone's rotation in the hierarchy?

**Comment by TabuuForteAkugun** [comment]
I'm not sure. I'm just saying it based on what DSX8 and Jam once told me. Some rotations haven't been figured it out yet. I wanted to try and help but I had no clue. :(

**Comment by tateplayer** [comment]
well, after having researched the format with a friend it looks like there really is no data there--they have a single static key. what happens in-game is that the unanimated joints use the data from the previous joint in order to determine its rotation.

in the gif below, i managed to replicate that equation and it came out quite nicely.

https://i.gyazo.com/8b991d967274f43a8abf1c5f70df5a4e.gif

i assume this is likely the case for a few other animations. it's definitely on more than half of Master Hand's animations. this being the case, i'll be closing this git issue.
