### ISSUE TITLE
Model textures not working correctly

### ISSUE THREAD

**Issue by lucas20pk** [jam1garner/Smash-Forge#94]
Whenever I go use smashforge I would go to file>open>open character like normal. I'd put in the character I want to look at(Falcon in this example) and this happens imgur.com/a/9k7Wq    I honestly don't know what I did wrong, so if someone can help that'd be neat.

**Comment by Demonslayerx8** [comment]
What's ur GPU and OpenGL version?

**Comment by lucas20pk** [comment]
GPU is Intel(R) HD Graphics

My OpengGL version I have no clue as it always stops working(using latest version

**Comment by Demonslayerx8** [comment]
the issue is most likely ur Intel GPU... it does not work well with Intel,
works properly with AMD or NVidia tho.

**Comment by lucas20pk** [comment]
Ah rip
