### ISSUE TITLE
Editing .NUT files through Smash Forge breaks Photoshop

### ISSUE THREAD

**Issue by Leocayn** [jam1garner/Smash-Forge#95]
The first time I open a .NUT file through the Smash Forge editor (and open with Photoshop CS4), everything runs perfectly fine. However, if I try to edit any further textures using the tool, Photoshop gives the error message, "Could not complete your request because of a disk error".

From this point forward, Photoshop becomes completely useless (even when performing tasks completely unrelated to modding such as opening and creating files) until I restart and, on some occasions, repair my hard drive. I'm not entirely sure whether Smash Forge is the cause of this, but I can consistently trigger this issue and it didn't begin until I began using the texture editor. 

I've searched all over for a solution to the Photoshop error and found nothing, and I've run several scans and repairs on my hard drive, but everything seems perfectly fine otherwise.

Any help in solving this would be greatly appreciated!

**Comment by Demonslayerx8** [comment]
the reason for that is cause the textures that fails to open in Photoshop
is due to textures having more than 4 mips, so the best way to solve that
is either save as png via noesis or paint.net

**Comment by Leocayn** [comment]
Ah, thank you for the answer. I figured it was something on Photoshop's end. I'll have to try Paint.net in the future for editing. Cheers!
