### ISSUE TITLE
[Feature Request / Enhancement] OS X/Linux builds of Smash Forge

### ISSUE THREAD

**Issue by hillexed** [jam1garner/Smash-Forge#99]
Last time a program became the dominant force for smash modding (Brawlbox), it remained windows-only. I'm sure there are many users running OSX or Linux who would like to take part in smash 4 modding, but currently cannot use Smash Forge because only windows builds are available. If possible, it would be great to set up a linux build and/or an OSX build of Smash Forge so that non-windows users can use Smash Forge.

I know openTK supports these platforms, so I suspect System.Windows.Forms is the main windows-only dependency that needs to have an alternative to support builds of these platforms.

Of course, I recognize that this would take a large effort, and it may be better to prioritize bugfixing for now, but when some developers have time I know I and others would greatly appreciate Linux and/or OSX support.

**Comment by mariogamer2** [comment]
:+1:

**Comment by jam1garner** [comment]
Feel free to make a PR, but due to poor practices mainly the fault of my own reworking the UI is likely not doable in a reasonable amount of effort to be justifiable for an unpaid side project.
